name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
  workflow_dispatch: # للسماح بتشغيل العمل يدويًا
    inputs:
      python_version:
        description: "Python version to use"
        default: "3.10"
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed "C:\Users\ccl\Desktop\مجلد جديد (3)\كود الحل السريع اوبن فينو (2).py"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-exe
        path: dist/*.exe
